### ISSUE TITLE
Two typos in the title of this repo.

### ISSUE THREAD

**Issue by ronperris** [nodejs/security-advisories#11]
## Currently:
Serurity advisories for Node.js and JavaScript ecosytem

## Should be:
Security advisories for Node.js and the JavaScript ecosystem.

**Comment by sam-github** [comment]
Oops. I don't know who has perms to fix this. @vdeturckheim ? @lirantal ?

**Comment by lirantal** [comment]
thanks @ronperris @sam-github, fixed.
