### ISSUE TITLE
Set up this repo

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/security-advisories#4]
* [x] add a script to sync up with security WG repo (#2 ) 
* [x] first sync up between both repos (#3 )
* [x] copy validation script to here and enable them in CI
* [x] set up CI-based synchronisation between the repos
* [ ] add Algolia upload script to CI
* [ ] move/build documentation for this repo (TBD)

**Comment by waveywaves** [comment]
I would like to start working on this issue :) Is anyone else working on this by any chance ?

**Comment by waveywaves** [comment]
Do check the PR at the https://github.com/nodejs/security-advisories/pull/7 wrt the CI based sync between repos

**Comment by mhdawson** [comment]
@vdeturckheim is this something you think we still need. It looks like it has not been sync'd for a while.

I was looking to see if we could rename the primary branch to main, but I'm wondering if we should just archive it instead.

**Comment by vdeturckheim** [comment]
@mhdawson +1 on archiving, I think the security WG situation makes this all unneeded now

**Comment by mhdawson** [comment]
Ok, will archive

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
